# Generated by Django 5.2.7 on 2025-11-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uems_app', '0004_alter_event_from_date_alter_event_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('organizer', 'Organizer'), ('attendee', 'Attendee')], default='attendee', max_length=20),
        ),
    ]
